export const ProductList = [
  { label: "Ammonium Lauryl Sulphate", val: "/cosmeceuticals/#Alcohol-Sulphate" },
  { label: "Alcohol Sulphate", val: "/cosmeceuticals/#Alcohol-Sulphate" },
  { label: "Disodium Laureth Sulfosuccinate", val: "/cosmeceuticals/#Alcohol-Sulphate" },
  { label: "Sodium Lauryl Ether Sulphate", val: "/cosmeceuticals/#Alcohol-Sulphate" },
  { label: "Sodium Lauryl Sulphate", val: "/cosmeceuticals/#Alcohol-Sulphate" },
  { label: "Benzoic acid", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Anti Oxidants", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Benzyl Alcohol", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Butylated Hydroxy Anisole (BHA)", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Butyl Hydroxy Toluene (BHT)", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Calcium Gluconate", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Caprylhydroxamic acid", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Chlorophenesin", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Ethylhexylglycerin", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Imidazolidinyl Urea", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Phenoxyethanol", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Tertiary Butyl Hydroquinone (TBHQ)", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Vitamin E Acetate", val: "/cosmeceuticals/#Anti-Oxidants" },
  { label: "Carrot root ferment filtrate", val: "/cosmeceuticals/#Bio-Ferments" },
  { label: "Coconut oil + Onion ferment", val: "/cosmeceuticals/#Bio-Ferments" },
  { label: "Radish root ferment", val: "/cosmeceuticals/#Bio-Ferments" },
  { label: "Rice ferment", val: "/cosmeceuticals/#Bio-Ferments" },
  { label: "Soya bean ferment", val: "/cosmeceuticals/#Bio-Ferments" },
  { label: "Bio Ferments", val: "/cosmeceuticals/#Bio-Ferments" },
  { label: "CAPB(Coco Amido Propyl Betaine)", val: "/cosmeceuticals/#Booster" },
  { label: "Booster", val: "/cosmeceuticals/#Booster" },
  { label: "Cocobetaine", val: "/cosmeceuticals/#Booster" },
  { label: "Cocodiethanolamide", val: "/cosmeceuticals/#Booster" },
  { label: "Cocomonoethanolamide", val: "/cosmeceuticals/#Booster" },
  { label: "Decyl Oleate", val: "/cosmeceuticals/#Booster" },
  { label: "Glyceryl Mono-Oleate", val: "/cosmeceuticals/#Booster" },
  { label: "Isodecyl Oleate", val: "/cosmeceuticals/#Booster" },
  { label: "Lauryl betaine", val: "/cosmeceuticals/#Booster" },
  { label: "Lauryl Lactate", val: "/cosmeceuticals/#Booster" },
  { label: "Myristyl Myristate", val: "/cosmeceuticals/#Booster" },
  { label: "Polyglyceryl oleate", val: "/cosmeceuticals/#Booster" },
  { label: "Sodium lactate", val: "/cosmeceuticals/#Booster" },
  { label: "Sodium lauryl lactylate", val: "/cosmeceuticals/#Booster" },
  { label: "Sorbitan Mono Palmitate", val: "/cosmeceuticals/#Booster" },
  { label: "Sorbitan Mono Stearate", val: "/cosmeceuticals/#Booster" },
  { label: "Tetraglyceryl monooleate", val: "/cosmeceuticals/#Booster" },
  { label: "Triglycerol Monosterate", val: "/cosmeceuticals/#Booster" },
  { label: "Guar Hydroxypropyltrimonium chloride (HPMC)", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "DL panthenol", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Conditioning Agents", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Glyceryl Tricaprylate", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Hydrolyzed pea protein", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Hydroxy Ethyl urea", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Hydrolyzed keratin", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Polyquaternium 37", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Polyquaternium 39", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Polyquaternium 10", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Polyquaternium 11", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Polyquaternium 22", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Polyquaternium 6", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Polyquaternium 7", val: "/cosmeceuticals/#Conditioning-Agents" },
  { label: "Ammonium thioglycolate", val: "/cosmeceuticals/#Hair-Care" },
  { label: "Capryloyl Glycine", val: "/cosmeceuticals/#Hair-Care" },
  { label: "Ciclopirox", val: "/cosmeceuticals/#Hair-Care" },
  { label: "Hair Care", val: "/cosmeceuticals/#Hair-Care" },
  { label: "Ciclopirox olamine", val: "/cosmeceuticals/#Hair-Care" },
  { label: "Piroctone olamine", val: "/cosmeceuticals/#Hair-Care" },
  { label: "Zinc Pyrithione", val: "/cosmeceuticals/#Hair-Care" },
  { label: "Aloe vera extract (water soluble)", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Citrus extract (water soluble)", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Liquorice extract (water soluble)", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Bamboo extract (water soluble)", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Turmeric extract (oil soluble)", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Neem Extract (water soluble)", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Cantella extract (water soluble)", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Green tea extract (water soluble)", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Resveratrol (non soluble)", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Green coffee bean extract (water soluble)", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Lutein (oil soluble)", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Liquid Extracts", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Flavonoids", val: "/cosmeceuticals/#Liquid-Extracts" },
  { label: "Biodegradable micro beads/scrub beads", val: "/cosmeceuticals/#Milliglobules" },
  { label: "Customized fruit & leaf lookalikes", val: "/cosmeceuticals/#Milliglobules" },
  { label: "Encapsulated Milliglobules", val: "/cosmeceuticals/#Milliglobules" },
  { label: "Millicapsules", val: "/cosmeceuticals/#Milliglobules" },
  { label: "Milliglobules", val: "/cosmeceuticals/#Milliglobules" },
  { label: "Alpha arbutin", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Aminexil", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Azelic acid", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Active", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Ascorbyl Glucoside", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Ascorbyl palmitate", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Beta arbutin", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Ethtyl ascoric acid", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Glycolic acid 99%", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Hyaluronic acid", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Keratin hydrolysate protein", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Kojic acid", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Kojic acid dipalmitate", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "L-Glutathione reduced", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Magnesium Ascorbyl Phosphate (MAP)", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Minoxidil", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Minoxidil sulphate", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Potassium hydroxide pellets", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Silk protein", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Sodium Ascorbyl phosphate", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Sodium Hyaluronate", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Wheat hyrdolysate protein", val: "/cosmeceuticals/#Active-&-Miscellaneous" },
  { label: "Allantoin", val: "/cosmeceuticals/#Moisturizers" },
  { label: "CCTG", val: "/cosmeceuticals/#Moisturizers" },
  { label: "Moisturizers", val: "/cosmeceuticals/#Moisturizers" },
  { label: "Glycerol Mono Stearate", val: "/cosmeceuticals/#Moisturizers" },
  { label: "Hydroxyethtyl Urea", val: "/cosmeceuticals/#Moisturizers" },
  { label: "Iso Propyl Myristate (IPM)", val: "/cosmeceuticals/#Moisturizers" },
  { label: "Iso Propyl palmitate (IPP)", val: "/cosmeceuticals/#Moisturizers" },
  { label: "Lauryl Lactate", val: "/cosmeceuticals/#Moisturizers" },
  { label: "Pullulan", val: "/cosmeceuticals/#Moisturizers" },
  { label: "Sodium Hyaluronate", val: "/cosmeceuticals/#Moisturizers" },
  { label: "Sodium PCA", val: "/cosmeceuticals/#Moisturizers" },
  { label: "Zinc PCA", val: "/cosmeceuticals/#Moisturizers" },
  { label: "Anise oil", val: "/cosmeceuticals/#Oils" },
  { label: "Argan Oil", val: "/cosmeceuticals/#Oils" },
  { label: "Oils", val: "/cosmeceuticals/#Oils" },
  { label: "Black cumin seed oil (kalonji)", val: "/cosmeceuticals/#Oils" },
  { label: "Borage Oil", val: "/cosmeceuticals/#Oils" },
  { label: "Carrot Seed oil", val: "/cosmeceuticals/#Oils" },
  { label: "Coconut oil", val: "/cosmeceuticals/#Oils" },
  { label: "Dill seed oil", val: "/cosmeceuticals/#Oils" },
  { label: "Eucalyptus oil", val: "/cosmeceuticals/#Oils" },
  { label: "Evening Primrose Oil", val: "/cosmeceuticals/#Oils" },
  { label: "Garlic oil", val: "/cosmeceuticals/#Oils" },
  { label: "Hempseed oil", val: "/cosmeceuticals/#Oils" },
  { label: "Lavender oil", val: "/cosmeceuticals/#Oils" },
  { label: "Lemon oil", val: "/cosmeceuticals/#Oils" },
  { label: "Linalool", val: "/cosmeceuticals/#Oils" },
  { label: "Linseed / Flaxseed oil", val: "/cosmeceuticals/#Oils" },
  { label: "Neem oil", val: "/cosmeceuticals/#Oils" },
  { label: "Peppermint Oil", val: "/cosmeceuticals/#Oils" },
  { label: "Spearmint oil", val: "/cosmeceuticals/#Oils" },
  { label: "Sunflower oil", val: "/cosmeceuticals/#Oils" },
  { label: "Turmeric oil", val: "/cosmeceuticals/#Oils" },
  { label: "Turpentine oil", val: "/cosmeceuticals/#Oils" },
  { label: "Wheatgerm oil", val: "/cosmeceuticals/#Oils" },
  { label: "Butyl Paraben", val: "/cosmeceuticals/#Parabens" },
  { label: "Ethyl Paraben", val: "/cosmeceuticals/#Parabens" },
  { label: "Methyl Paraben", val: "/cosmeceuticals/#Parabens" },
  { label: "Parabens", val: "/cosmeceuticals/#Parabens" },
  { label: "Propyl Paraben", val: "/cosmeceuticals/#Parabens" },
  { label: "Sodium Butyl Paraben", val: "/cosmeceuticals/#Parabens" },
  { label: "Sodium Ethyl Paraben", val: "/cosmeceuticals/#Parabens" },
  { label: "Sodium Methyl Paraben", val: "/cosmeceuticals/#Parabens" },
  { label: "Sodium Propyl Paraben", val: "/cosmeceuticals/#Parabens" },
  { label: "Ethylene Glycol Distearate", val: "/cosmeceuticals/#Pearlising-Agents" },
  { label: "Ethylene Glycol Monostearate", val: "/cosmeceuticals/#Pearlising-Agents" },
  { label: "Hydrolyzed Barley protein", val: "/cosmeceuticals/#Protein" },
  { label: "Hydrolyzed Collagen", val: "/cosmeceuticals/#Protein" },
  { label: "Hydrolyzed Keratin", val: "/cosmeceuticals/#Protein" },
  { label: "Proteins", val: "/cosmeceuticals/#Protein" },
  { label: "Hydrolyzed Linseed seed", val: "/cosmeceuticals/#Protein" },
  { label: "Hydrolyzed Milk protein", val: "/cosmeceuticals/#Protein" },
  { label: "Hydrolyzed Oat protein", val: "/cosmeceuticals/#Protein" },
  { label: "Hydrolyzed Quinoa", val: "/cosmeceuticals/#Protein" },
  { label: "Hydrolyzed Rice protein", val: "/cosmeceuticals/#Protein" },
  { label: "Hydrolyzed Soy protein", val: "/cosmeceuticals/#Protein" },
  { label: "Calcium thioglycolate", val: "/cosmeceuticals/#Skin-Care" },
  { label: "DL-Mandelic acid", val: "/cosmeceuticals/#Skin-Care" },
  { label: "Skin Care", val: "/cosmeceuticals/#Skin-Care" },
  { label: "Isorbide-2,5 dithioglycolate", val: "/cosmeceuticals/#Skin-Care" },
  { label: "Lauryl Lactyl Lactate", val: "/cosmeceuticals/#Skin-Care" },
  { label: "Magnolol", val: "/cosmeceuticals/#Skin-Care" },
  { label: "n-Butyl Resorcinol", val: "/cosmeceuticals/#Skin-Care" },
  { label: "Potassium thioglycolate", val: "/cosmeceuticals/#Skin-Care" },
  { label: "Sodium lauryl lactylate", val: "/cosmeceuticals/#Skin-Care" },
  { label: "Avobenzone", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Benzophenone 3 / Oxybenzone", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Bisoctrizole", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Calamine Powder", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Caprylic Capric Triglyceride (CCTG)", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Diethylhexyl butamido triazone", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Ethylhexyl Triazone", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Homosalate", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Sunscreens", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Octocrylene", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Octyl Methoxy Cinnamate (OMC) / Octinoxate", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Octyl Salicylate / Octisilate", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Titanium di oxide", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Zinc oxide", val: "/cosmeceuticals/#Sunscreens" },
  { label: "Avocado butter", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Beeswax Natural Pure", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Wax & Butter", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Beeswax White", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Beeswax Yellow", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Candelilla Wax", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Carnauba Wax", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Ceresin Wax White", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Cocoa butter", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Emulsifying Wax Anionic", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Emulsifying Wax Non ionic", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Kokum butter", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Mango butter", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Microcrystalline Wax White", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Olive butter", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Paraffin Wax", val: "/cosmeceuticals/#Wax-&-Butter" },
  { label: "Shea butter", val: "/cosmeceuticals/#Wax-&-Butter" }
];
